apiVersion: v1
kind: Pod
metadata:
  name: javaapi
  labels:
    app: javaapi
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
    - image: java-api
      name: javaapi
      imagePullPolicy: IfNotPresent
      resources: {}
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo

  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
